[package]
name = "contpyif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "contpyif"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
rosrust = "0.9.10"
rosrust_msg = "0.1.6"
serial = "0.4.0"
